(function () {
    'use strict';

    var REPORT = null;
    var SUMMARY = [];
    var RECORDS = [];
    var dataLoaded = false;

    var STATUS_PILL = {
        Enrolled: 'status-green',
        Pending: 'status-amber',
        Cancelled: 'status-red'
    };

    var STATUS_ICON = {
        Enrolled: 'fa-circle-check',
        Pending: 'fa-hourglass-half',
        Cancelled: 'fa-circle-xmark'
    };

    var MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

    var state = {
        page: 1,
        size: 5
    };

    var lastTotal = 1;

    function pad(n) {
        return String(n).padStart(2, '0');
    }

    function fmtDate(date) {
        if (!date || !(date instanceof Date) || isNaN(date.getTime())) return '—';
        return MONTHS[date.getMonth()] + ' ' + pad(date.getDate()) + ', ' + date.getFullYear();
    }

    function initials(name) {
        return String(name || '').split(/\s+/).filter(function (p) { return p; })
            .slice(0, 2).map(function (p) { return p[0].toUpperCase(); })
            .join('');
    }

    function showToast(message, type) {
        var toast = document.querySelector('#cec-toast');
        if (!toast) {
            toast = document.createElement('div');
            toast.id = 'cec-toast';
            toast.className = 'toast';
            toast.setAttribute('role', 'status');
            document.body.appendChild(toast);
        }
        toast.className = 'toast show ' + (type ? 'toast-' + type : '');
        toast.innerHTML = '<i class="fa-solid ' + (type === 'error' ? 'fa-circle-exclamation' : type === 'success' ? 'fa-circle-check' : 'fa-circle-info') + '" aria-hidden="true"></i>' + message;
        clearTimeout(toast._timer);
        toast._timer = setTimeout(function () {
            toast.className = 'toast';
        }, 2600);
    }

    function metaSkeletonHtml() {
        var html = '';
        for (var i = 0; i < 4; i++) {
            html += '<div class="meta-item"><div class="skeleton meta-skel"></div><div class="skeleton meta-skel" style="width:70%"></div></div>';
        }
        return html;
    }

    function renderMeta() {
        var grid = document.getElementById('meta-grid');
        if (!grid) return;
        grid.innerHTML = metaSkeletonHtml();

        setTimeout(function () {
            var meta = REPORT || {};
            grid.innerHTML =
                '<div class="meta-item"><span>Report Type</span><strong>' + (meta.type || 'Enrollment Report') + '</strong></div>' +
                '<div class="meta-item"><span>Date Range</span><strong>' + (meta.dateRange || '—') + '</strong></div>' +
                '<div class="meta-item"><span>Generated On</span><strong>' + (meta.generatedOn || '—') + '</strong></div>' +
                '<div class="meta-item"><span>Generated By</span><strong>' + (meta.generatedBy || '—') + '</strong></div>';
        }, 500);
    }

    function summaryCardHtml(item) {
        var icon = item.trend === 'up' ? 'fa-arrow-trend-up' : 'fa-arrow-trend-down';
        return '<article class="stat-card">' +
            '<span class="stat-icon"><i class="' + item.icon + '" aria-hidden="true"></i></span>' +
            '<div class="stat-info">' +
            '<p>' + item.label + '</p>' +
            '<strong>' + item.value + '</strong>' +
            '<small>' + item.sub + '</small>' +
            '</div>' +
            '<span class="trend-badge ' + item.trend + '"><i class="fa-solid ' + icon + '" aria-hidden="true"></i> ' + item.trendText + '</span>' +
            '</article>';
    }

    function kpiSkeletonHtml() {
        return '<article class="kpi-skeleton">' +
            '<div class="skeleton s-icon"></div>' +
            '<div class="skeleton s-line short"></div>' +
            '<div class="skeleton s-line value"></div>' +
            '<div class="skeleton s-line" style="width:35%"></div>' +
            '</article>';
    }

    function renderSummary() {
        var grid = document.getElementById('summary-grid');
        if (!grid) return;
        grid.innerHTML = kpiSkeletonHtml() + kpiSkeletonHtml() + kpiSkeletonHtml() + kpiSkeletonHtml();

        setTimeout(function () {
            grid.innerHTML = SUMMARY.length ? SUMMARY.map(summaryCardHtml).join('') : '<p class="empty-copy">No summary data available.</p>';
        }, 500);
    }

    function rowHtml(record) {
        var pill = STATUS_PILL[record.status] || 'status-amber';
        var icon = STATUS_ICON[record.status] || 'fa-circle-info';
        return '<tr>' +
            '<td class="cell-id">' + record.id + '</td>' +
            '<td><div class="user-cell">' +
            '<span class="mini-avatar">' + initials(record.studentName) + '</span>' +
            '<span class="user-meta"><strong>' + record.studentName + '</strong></span>' +
            '</div></td>' +
            '<td>' + record.program + '</td>' +
            '<td>' + record.yearLevel + '</td>' +
            '<td class="username-cell">' + fmtDate(record.enrollmentDate) + '</td>' +
            '<td><span class="status-badge ' + pill + '"><i class="fa-solid ' + icon + '" aria-hidden="true"></i> ' + record.status + '</span></td>' +
            '</tr>';
    }

    function skeletonRowsHtml() {
        var html = '';
        for (var i = 0; i < 5; i++) {
            html += '<tr><td colspan="6"><div class="skeleton row-skel"></div></td></tr>';
        }
        return html;
    }

    function pageList(current, total) {
        var wanted = {};
        var add = function (n) {
            if (n >= 1 && n <= total) wanted[n] = true;
        };
        add(1);
        add(total);
        for (var w = current - 2; w <= current + 2; w++) add(w);
        var keys = Object.keys(wanted).map(Number).sort(function (a, b) { return a - b; });
        var out = [];
        for (var i = 0; i < keys.length; i++) {
            if (i > 0 && keys[i] - keys[i - 1] > 1) out.push('...');
            out.push(keys[i]);
        }
        return out;
    }

    function renderRows() {
        var tbody = document.getElementById('report-tbody');
        var indicator = document.getElementById('record-indicator');
        if (!tbody) return;

        lastTotal = Math.max(1, Math.ceil(RECORDS.length / state.size));
        if (state.page > lastTotal) state.page = lastTotal;
        if (state.page < 1) state.page = 1;

        var start = (state.page - 1) * state.size;
        var pageItems = RECORDS.slice(start, start + state.size);

        tbody.innerHTML = pageItems.length
            ? pageItems.map(rowHtml).join('')
            : '<tr class="empty-row"><td colspan="6">No enrollment records available.</td></tr>';

        if (indicator) {
            var from = RECORDS.length ? start + 1 : 0;
            indicator.textContent = 'Showing ' + from + ' - ' + (start + pageItems.length) + ' of ' + RECORDS.length;
        }

        renderPagination();
    }

    function renderPagination() {
        var container = document.getElementById('page-numbers');
        if (!container) return;

        var html = '';
        pageList(state.page, lastTotal).forEach(function (entry) {
            if (entry === '...') {
                html += '<span class="page-ellipsis" aria-hidden="true">…</span>';
            } else {
                html += '<button type="button" class="page-num' + (entry === state.page ? ' active' : '') + '" data-page="' + entry + '">' + entry + '</button>';
            }
        });
        container.innerHTML = html;

        var prev = document.getElementById('prev-page');
        var next = document.getElementById('next-page');
        if (prev) prev.disabled = state.page <= 1;
        if (next) next.disabled = state.page >= lastTotal;
    }

    function loadReport() {
        var tbody = document.getElementById('report-tbody');
        if (tbody) tbody.innerHTML = skeletonRowsHtml();

        if (dataLoaded) {
            renderMeta();
            renderSummary();
            renderRows();
            return;
        }

        API.get('/admin/reports/enrollment').then(function (res) {
            dataLoaded = true;
            var d = (res && typeof res === 'object') ? res : {};
            REPORT = d.report || d.meta || {};
            SUMMARY = d.summary || [];
            var items = (d.records && Array.isArray(d.records)) ? d.records : ((res && Array.isArray(res)) ? res : []);
            RECORDS = items.map(function (r) {
                var copy = {};
                Object.keys(r).forEach(function (k) { copy[k] = r[k]; });
                if (copy.enrollmentDate) copy.enrollmentDate = new Date(copy.enrollmentDate);
                return copy;
            });
            renderMeta();
            renderSummary();
            renderRows();
        }).catch(function (err) {
            dataLoaded = true;
            if (tbody) tbody.innerHTML = '<tr class="empty-row"><td colspan="6">Failed to load report data. ' + ((err && err.message) ? err.message : 'Server unreachable.') + '</td></tr>';
            showToast('Failed to load report data.', 'error');
        });
    }

    function bindPagination() {
        var numbers = document.getElementById('page-numbers');
        if (numbers) {
            numbers.addEventListener('click', function (e) {
                var btn = e.target.closest('.page-num');
                if (btn && !btn.classList.contains('active')) {
                    state.page = parseInt(btn.getAttribute('data-page'), 10);
                    loadReport();
                }
            });
        }

        var prev = document.getElementById('prev-page');
        var next = document.getElementById('next-page');
        if (prev) prev.addEventListener('click', function () { if (state.page > 1) { state.page--; loadReport(); } });
        if (next) next.addEventListener('click', function () { if (state.page < lastTotal) { state.page++; loadReport(); } });
    }

    function downloadSimulation(label, id) {
        var buttons = document.querySelectorAll('#' + id);
        if (buttons.length) buttons[0].classList.add('btn-spin');
        showToast('Preparing ' + label + ' for report ' + (REPORT && REPORT.id ? REPORT.id : 'the report') + '...', '');
        setTimeout(function () {
            if (buttons.length) buttons[0].classList.remove('btn-spin');
            showToast(label + ' download ready.', 'success');
        }, 1000);
    }

    function bindActions() {
        var pdfBtn = document.getElementById('pdf-btn');
        var excelBtn = document.getElementById('excel-btn');
        var printBtn = document.getElementById('print-btn');
        if (pdfBtn) pdfBtn.addEventListener('click', function () { downloadSimulation('PDF', 'pdf-btn'); });
        if (excelBtn) excelBtn.addEventListener('click', function () { downloadSimulation('Excel', 'excel-btn'); });
        if (printBtn) printBtn.addEventListener('click', function () { window.print(); });
    }

    document.addEventListener('DOMContentLoaded', function () {
        bindPagination();
        bindActions();
        loadReport();
    });
})();